url: 
baseurl: 

# Site settings
title: Dagaa
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Adolfo Cota
  pic: 1
  position: Tech alchemist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Diana Cordova
  pic: 2
  position: Administration and Finance
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Emmanuel Galvan
  pic: 3
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jose Juan Madrigal
  pic: 4
  position: Mechanical Design Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Juan Carlos Rojas
  pic: 5
  position: Electronics and Programming Creator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #  

- name: Cesar Humberto Galindo
  pic: 6
  position: Design and Manufacturing Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/dagaa_development/
  - title: facebook
    url: https://www.facebook.com/dagaaEngineering/
  - title: twitter
    url: https://twitter.com/dagaadevelop
  - title: github
    url: https://github.com/orgs/dagaa-development/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
